### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by vincentchalamon** [lafourchette/SwitchUserStatelessBundle#11]
It could be wonderful to create a release/tag for this project

**Comment by krlove** [comment]
+1

**Comment by chalasr** [comment]
👍  We recommend this bundle in `LexikJWTAuthenticationBundle`, it would be quite better to have a stable version.

**Comment by vincentchalamon** [comment]
Ping @jshedde: can you create a release, please?

**Comment by jshedde** [comment]
I have created a v0.1.0.

Is it good for you ?

**Comment by vincentchalamon** [comment]
Thank you @jshedde
