### ISSUE TITLE
Use the vendor name in the namespace

### ISSUE THREAD

**Issue by dunglas** [lafourchette/SwitchUserStatelessBundle#4]
Should be `LaFourchette\SwitchUserStatelessBundle` or `TheFork\SwitchUserStatelessBundle`. What do you think?

**Comment by vincentchalamon** [comment]
Ping @jshedde: what do you think about it?

**Comment by MLKiiwy** [comment]
interesting question !!!

**Comment by jshedde** [comment]
Our public repositories (github, packagist...) are branded with "lafourchette". I think it would be confusing to use TheFork vendor name.

**Comment by vincentchalamon** [comment]
So @jshedde `LaFourchette\SwitchUserStatelessBundle`?

**Comment by jshedde** [comment]
yes!
